#PBS -S /bin/bash
#PBS -N squad_train_dual
#PBS -j oe
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=24:ngpus=2:mem=20gb
##PBS -q gpuq
#PBS -q isiaq
#PBS -P isia

# Go to the current directory 
cd $PBS_O_WORKDIR

# Load the same modules as for compilation 
module load anaconda3/5.3.1
source activate transformers_env

# Path to dataset
export SQUAD_DIR=/gpfs/opt/data/squad/1.1
#export SQUAD_DIR=/gpfs/opt/data/squad/2.0

# Run code
python main.py